blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


from users.apps import UsersConfig
from .views import RegisterView, UserUpdateView, confirm_email, activate_email, password_reset

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),

    path('confirm', confirm_email, name='confirm'),
    path('activate<str:key>', activate_email, name='activate'),
    path('password_reset/', password_reset, name='password_reset'),

]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.CharField(max_length=100, verbose_name='описание')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображеие', **NULLABLE)
    creation_date = models.TimeField(verbose_name='дата создания', auto_now_add=True)

    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    sign_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}, {self.description}'

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "статьи"

blog/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

from blog.models import Blog
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'description', 'preview', 'sign_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogListView(ListView):
    """Контроллер блога для просмотра списка статей"""
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(sign_published=True)
        return queryset


class BlogDetailView(DetailView):
    """Контроллер блога для детального просмотра статьи"""

    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    """Контроллер блога для редактирования статьи"""

    model = Blog
    fields = ('title', 'description', 'preview', 'sign_published', )

    def get_success_url(self):
        """
        Переопределение url-адреса для перенаправления
        после успешного редактирования
        """

        return reverse('blog:view', args=[self.object.pk])


class BlogDelete(DeleteView):
    """Контроллер блога для удаления статьи"""

    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
</div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить статью {{object.title}}?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load media_path %}
<div class="col-12">
    <div class="row">
        <figure class="figure">
                 <img src="{{ blog.preview|media_path }}" class="img-fluid" alt="{{ blog.image }} 300x200" width="300" height="200">
            </figure>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title>">
                        Информация о продукте
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Название</td>
                            <td>{{ blog.title }}</td>
                        </tr>
                        <tr>
                            <td>Информация</td>
                            <td>{{ blog.description }}</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<br>
<h1 align="center">Добавление новой статьи</h1><br><br>
<div class="row"><br>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>
</div>

{% if user.is_authenticated %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
</div>
{% else %}
<div class="col-3">
    <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Войдите, чтобы добавить статью</a>
</div>
        {% endif %}
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {{ object.title }}
                </p>
                <div class="">
                    <div class="btn-group">
                        <a href="{% url 'blog:view' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'blog:edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'blog:delete' object.pk %}"
                           class="btn btn-sm btn-outline-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endfor %}

{% endblock %}