blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


from users.apps import UsersConfig
from .views import RegisterView, UserUpdateView, confirm_email, activate_email, password_reset

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),

    path('confirm', confirm_email, name='confirm'),
    path('activate<str:key>', activate_email, name='activate'),
    path('password_reset/', password_reset, name='password_reset'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from blog.models import NULLABLE


# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    email_confirmed = models.BooleanField(default=False, verbose_name='подтверждено')
    email_key = models.CharField(max_length=30, verbose_name='код подтверждения почты', **NULLABLE)

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(**NULLABLE, verbose_name='страна')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "phone", "country", "avatar", "password1", "password2"]


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "password", "first_name", "last_name", "phone", "country", "avatar"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordResetDoneView
from django.conf import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User

from users.utils import confirm_user_email, create_secret_key


class RegisterView(CreateView):
    """ Регистрация нового пользователя и отправка подтверждения на email пользователя """
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class UserUpdateView(UpdateView):
    """Профиль пользователя """
    model = User
    success_url = reverse_lazy("users:profile")
    form_class = UserProfileForm
    template_name = "users/user_detail.html"

    def get_object(self, queryset=None):
        return self.request.user


def confirm_email(request):
    """подтверждаем почту"""
    confirm_user_email(request, request.user)
    return redirect(reverse('users:profile'))


def activate_email(request, key):
    """активируем почту"""
    print(request.user.email_key, key, sep='\n')
    if request.user.email_key == key:
        request.user.email_confirmed = True
        request.user.email_key = None
        request.user.save()

    else:
        print('Ключ не актуален')
        print(request.user.email_key, key, sep='\n')
    return redirect('/')


def password_reset(request):
    """генерируем пароль для неавторизованного пользователя"""
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = create_secret_key(12)
            user.set_password(new_password)
            user.save()
            login(request, user)

            send_mail(
                subject='Вы запросили смену пароля',
                message=f'Ваш новый пароль: {new_password}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[request.user.email]
            )

            return redirect(reverse("users:login"))# все ок -> логин
        # не ок -> Error message + остаемся тут же
        except User.DoesNotExist:
            return render(request, 'users/password_reset_form.html',
                          {'error_message': 'Такого пользователя не существует'})
    return render(request, 'users/password_reset_form.html')

users/templates/users/confirm_email_message.html
{% autoescape off %}
Перейдите по ссылке, чтобы подтвердить почту:
http://{{ domain }}{% url 'users:activate' key %}
{% endautoescape %}

users/templates/users/login.html
 {% extends 'catalog/base.html' %}
{% block content%}
<div class="row mt-2 justify-content-center">
    <div class="col-6">
        <div class="card text-center">
          <div class="card-body">
            <h4 class="card-title">Вход</h4>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Войти">
                    <a href="{% url 'users:password_reset'  %}" class="btn btn-success">Забыл пароль</a>
                </div>
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<h2>Забыли свой пароль?</h2>
<p>Введите свой адрес электронной почты, чтобы получить новый пароль.</p>

<form method="post">
{% csrf_token %}
<input type="email" name="email" placeholder="Email" required>
<button type="submit">Отправить e-mail</button>
</form>

{% if error_message %}
<p style="color:red;">{{ error_message }}</p>
{% endif %}

{% endblock %}

users/templates/users/register.html
 {% extends 'catalog/base.html' %}
{% block content%}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class='card'>
               <div class="card-header">
                   <h4 class="card-title">
                       Регистрация
                   <small class="text-body-secondary">(после регистрации вам необходимо подтвердить почту в вашем Профиле)</small>
                   </h4>
               </div>
                   <div class='col-8 mb-4'>
                       <div class="card">
                           <div class="card-body" >
                                   {%csrf_token%}
                                   {{ form.as_p }}
                                   <button type="submit" class="btn btn-success">
                                        Зарегистрироваться
                                   </button>
                           </div>
                       </div>
                   </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load media_path %}

<div class="row">
    <div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <figure class="figure">
                 <img src="{{ user.avatar|media_path }}" class="img-fluid" alt="{{ user.avatar }} 300x200" width="300" height="200">
            </figure>
                {% if object.email_confirmed%}
                    <form method="post">
                    {%  csrf_token %}
                    {{ form.as_p}}
                <p><button type="submit" class="btn btn-success">Сохранить</button></p>
                </form>
                {% else %}
                        <p class="card-text">Почта: {{ object.email }}
                        <a href="{% url 'users:confirm' %}" class="btn btn-sm btn-danger">Подтвердить почту</a>
                        <h3>
                       </h3>
                      {% endif %}<br>

            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="row">
    <div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {%  csrf_token %}
                    {{ form.as_p}}
                <p><button type="submit" class="btn btn-success">Сохранить</button></p>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}